baseurl                  = "https://salmanlee.github.io/youth77"               # Your domain name. Must end with "/"
languageCode             = "zh-cn"
title                    = "Youth77"
theme                    = "sam"
pygmentsStyle            = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "2006/01/02"
    dateformfull         = "2006/01/02 15:04:05 WST"
    favicon              = "/7.png"
    homepage             = "首页"                        # What to call the home page link
    galleryFolder        = "images/"                     # Where you've put your images, after "/content/gallery/" (eg. "images/")
    clickablePhotos      = true                          # Allow links to the full size images
    smallPreviewImages   = true                          # Show thumbnails (small images) instead of using full size images on the gallery page
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # Folder for image thumbnails (small versions) after "/content/gallery/[galleryFolder]" (eg. "small/")
                                                         # For each image the small version has to have the same filename as the big version.
    footerText           = "Youth77's site, a slob's site."

# Metadata
    description          = "Welcome to my site."            # Max 160 characters show in search results
    twitterCard          = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage         = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "博客"

[[params.mainMenu]]
    link = "/gallery"
    text = "相册"

[[params.mainMenu]]
    link = "/about"
    text = "关于"
    
